# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Action(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'TrelloID',
        'id_member_creator': 'TrelloID',
        'data': 'ActionData',
        'type': 'str',
        '_date': 'datetime',
        'limits': 'ActionLimits',
        'display': 'ActionDisplay',
        'member_creator': 'ActionMemberCreator'
    }

    attribute_map = {
        'id': 'id',
        'id_member_creator': 'idMemberCreator',
        'data': 'data',
        'type': 'type',
        '_date': 'date',
        'limits': 'limits',
        'display': 'display',
        'member_creator': 'memberCreator'
    }

    def __init__(self, id=None, id_member_creator=None, data=None, type=None, _date=None, limits=None, display=None, member_creator=None):  # noqa: E501
        """Action - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._id_member_creator = None
        self._data = None
        self._type = None
        self.__date = None
        self._limits = None
        self._display = None
        self._member_creator = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if id_member_creator is not None:
            self.id_member_creator = id_member_creator
        if data is not None:
            self.data = data
        if type is not None:
            self.type = type
        if _date is not None:
            self._date = _date
        if limits is not None:
            self.limits = limits
        if display is not None:
            self.display = display
        if member_creator is not None:
            self.member_creator = member_creator

    @property
    def id(self):
        """Gets the id of this Action.  # noqa: E501


        :return: The id of this Action.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Action.


        :param id: The id of this Action.  # noqa: E501
        :type: TrelloID
        """

        self._id = id

    @property
    def id_member_creator(self):
        """Gets the id_member_creator of this Action.  # noqa: E501


        :return: The id_member_creator of this Action.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id_member_creator

    @id_member_creator.setter
    def id_member_creator(self, id_member_creator):
        """Sets the id_member_creator of this Action.


        :param id_member_creator: The id_member_creator of this Action.  # noqa: E501
        :type: TrelloID
        """

        self._id_member_creator = id_member_creator

    @property
    def data(self):
        """Gets the data of this Action.  # noqa: E501


        :return: The data of this Action.  # noqa: E501
        :rtype: ActionData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Action.


        :param data: The data of this Action.  # noqa: E501
        :type: ActionData
        """

        self._data = data

    @property
    def type(self):
        """Gets the type of this Action.  # noqa: E501


        :return: The type of this Action.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Action.


        :param type: The type of this Action.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def _date(self):
        """Gets the _date of this Action.  # noqa: E501


        :return: The _date of this Action.  # noqa: E501
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this Action.


        :param _date: The _date of this Action.  # noqa: E501
        :type: datetime
        """

        self.__date = _date

    @property
    def limits(self):
        """Gets the limits of this Action.  # noqa: E501


        :return: The limits of this Action.  # noqa: E501
        :rtype: ActionLimits
        """
        return self._limits

    @limits.setter
    def limits(self, limits):
        """Sets the limits of this Action.


        :param limits: The limits of this Action.  # noqa: E501
        :type: ActionLimits
        """

        self._limits = limits

    @property
    def display(self):
        """Gets the display of this Action.  # noqa: E501


        :return: The display of this Action.  # noqa: E501
        :rtype: ActionDisplay
        """
        return self._display

    @display.setter
    def display(self, display):
        """Sets the display of this Action.


        :param display: The display of this Action.  # noqa: E501
        :type: ActionDisplay
        """

        self._display = display

    @property
    def member_creator(self):
        """Gets the member_creator of this Action.  # noqa: E501


        :return: The member_creator of this Action.  # noqa: E501
        :rtype: ActionMemberCreator
        """
        return self._member_creator

    @member_creator.setter
    def member_creator(self, member_creator):
        """Sets the member_creator of this Action.


        :param member_creator: The member_creator of this Action.  # noqa: E501
        :type: ActionMemberCreator
        """

        self._member_creator = member_creator

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Action, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Action):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
