# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ActionDisplayEntitiesContextOn(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'translation_key': 'str',
        'hide_if_context': 'bool',
        'id_context': 'TrelloID'
    }

    attribute_map = {
        'type': 'type',
        'translation_key': 'translationKey',
        'hide_if_context': 'hideIfContext',
        'id_context': 'idContext'
    }

    def __init__(self, type=None, translation_key=None, hide_if_context=None, id_context=None):  # noqa: E501
        """ActionDisplayEntitiesContextOn - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._translation_key = None
        self._hide_if_context = None
        self._id_context = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if translation_key is not None:
            self.translation_key = translation_key
        if hide_if_context is not None:
            self.hide_if_context = hide_if_context
        if id_context is not None:
            self.id_context = id_context

    @property
    def type(self):
        """Gets the type of this ActionDisplayEntitiesContextOn.  # noqa: E501


        :return: The type of this ActionDisplayEntitiesContextOn.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ActionDisplayEntitiesContextOn.


        :param type: The type of this ActionDisplayEntitiesContextOn.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def translation_key(self):
        """Gets the translation_key of this ActionDisplayEntitiesContextOn.  # noqa: E501


        :return: The translation_key of this ActionDisplayEntitiesContextOn.  # noqa: E501
        :rtype: str
        """
        return self._translation_key

    @translation_key.setter
    def translation_key(self, translation_key):
        """Sets the translation_key of this ActionDisplayEntitiesContextOn.


        :param translation_key: The translation_key of this ActionDisplayEntitiesContextOn.  # noqa: E501
        :type: str
        """

        self._translation_key = translation_key

    @property
    def hide_if_context(self):
        """Gets the hide_if_context of this ActionDisplayEntitiesContextOn.  # noqa: E501


        :return: The hide_if_context of this ActionDisplayEntitiesContextOn.  # noqa: E501
        :rtype: bool
        """
        return self._hide_if_context

    @hide_if_context.setter
    def hide_if_context(self, hide_if_context):
        """Sets the hide_if_context of this ActionDisplayEntitiesContextOn.


        :param hide_if_context: The hide_if_context of this ActionDisplayEntitiesContextOn.  # noqa: E501
        :type: bool
        """

        self._hide_if_context = hide_if_context

    @property
    def id_context(self):
        """Gets the id_context of this ActionDisplayEntitiesContextOn.  # noqa: E501


        :return: The id_context of this ActionDisplayEntitiesContextOn.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id_context

    @id_context.setter
    def id_context(self, id_context):
        """Sets the id_context of this ActionDisplayEntitiesContextOn.


        :param id_context: The id_context of this ActionDisplayEntitiesContextOn.  # noqa: E501
        :type: TrelloID
        """

        self._id_context = id_context

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionDisplayEntitiesContextOn, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionDisplayEntitiesContextOn):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
