# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CardsidCardcustomFieldsValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'checked': 'bool',
        '_date': 'datetime',
        'number': 'float'
    }

    attribute_map = {
        'text': 'text',
        'checked': 'checked',
        '_date': 'date',
        'number': 'number'
    }

    def __init__(self, text=None, checked=None, _date=None, number=None):  # noqa: E501
        """CardsidCardcustomFieldsValue - a model defined in Swagger"""  # noqa: E501
        self._text = None
        self._checked = None
        self.__date = None
        self._number = None
        self.discriminator = None
        if text is not None:
            self.text = text
        if checked is not None:
            self.checked = checked
        if _date is not None:
            self._date = _date
        if number is not None:
            self.number = number

    @property
    def text(self):
        """Gets the text of this CardsidCardcustomFieldsValue.  # noqa: E501


        :return: The text of this CardsidCardcustomFieldsValue.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this CardsidCardcustomFieldsValue.


        :param text: The text of this CardsidCardcustomFieldsValue.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def checked(self):
        """Gets the checked of this CardsidCardcustomFieldsValue.  # noqa: E501


        :return: The checked of this CardsidCardcustomFieldsValue.  # noqa: E501
        :rtype: bool
        """
        return self._checked

    @checked.setter
    def checked(self, checked):
        """Sets the checked of this CardsidCardcustomFieldsValue.


        :param checked: The checked of this CardsidCardcustomFieldsValue.  # noqa: E501
        :type: bool
        """

        self._checked = checked

    @property
    def _date(self):
        """Gets the _date of this CardsidCardcustomFieldsValue.  # noqa: E501


        :return: The _date of this CardsidCardcustomFieldsValue.  # noqa: E501
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this CardsidCardcustomFieldsValue.


        :param _date: The _date of this CardsidCardcustomFieldsValue.  # noqa: E501
        :type: datetime
        """

        self.__date = _date

    @property
    def number(self):
        """Gets the number of this CardsidCardcustomFieldsValue.  # noqa: E501


        :return: The number of this CardsidCardcustomFieldsValue.  # noqa: E501
        :rtype: float
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this CardsidCardcustomFieldsValue.


        :param number: The number of this CardsidCardcustomFieldsValue.  # noqa: E501
        :type: float
        """

        self._number = number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CardsidCardcustomFieldsValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CardsidCardcustomFieldsValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
