# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomFieldDisplayOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'TrelloID',
        'id_custom_field': 'TrelloID',
        'value': 'CustomFieldDisplayValue',
        'color': 'str',
        'pos': 'float'
    }

    attribute_map = {
        'id': 'id',
        'id_custom_field': 'idCustomField',
        'value': 'value',
        'color': 'color',
        'pos': 'pos'
    }

    def __init__(self, id=None, id_custom_field=None, value=None, color=None, pos=None):  # noqa: E501
        """CustomFieldDisplayOptions - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._id_custom_field = None
        self._value = None
        self._color = None
        self._pos = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if id_custom_field is not None:
            self.id_custom_field = id_custom_field
        if value is not None:
            self.value = value
        if color is not None:
            self.color = color
        if pos is not None:
            self.pos = pos

    @property
    def id(self):
        """Gets the id of this CustomFieldDisplayOptions.  # noqa: E501


        :return: The id of this CustomFieldDisplayOptions.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CustomFieldDisplayOptions.


        :param id: The id of this CustomFieldDisplayOptions.  # noqa: E501
        :type: TrelloID
        """

        self._id = id

    @property
    def id_custom_field(self):
        """Gets the id_custom_field of this CustomFieldDisplayOptions.  # noqa: E501


        :return: The id_custom_field of this CustomFieldDisplayOptions.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id_custom_field

    @id_custom_field.setter
    def id_custom_field(self, id_custom_field):
        """Sets the id_custom_field of this CustomFieldDisplayOptions.


        :param id_custom_field: The id_custom_field of this CustomFieldDisplayOptions.  # noqa: E501
        :type: TrelloID
        """

        self._id_custom_field = id_custom_field

    @property
    def value(self):
        """Gets the value of this CustomFieldDisplayOptions.  # noqa: E501


        :return: The value of this CustomFieldDisplayOptions.  # noqa: E501
        :rtype: CustomFieldDisplayValue
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this CustomFieldDisplayOptions.


        :param value: The value of this CustomFieldDisplayOptions.  # noqa: E501
        :type: CustomFieldDisplayValue
        """

        self._value = value

    @property
    def color(self):
        """Gets the color of this CustomFieldDisplayOptions.  # noqa: E501


        :return: The color of this CustomFieldDisplayOptions.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this CustomFieldDisplayOptions.


        :param color: The color of this CustomFieldDisplayOptions.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def pos(self):
        """Gets the pos of this CustomFieldDisplayOptions.  # noqa: E501


        :return: The pos of this CustomFieldDisplayOptions.  # noqa: E501
        :rtype: float
        """
        return self._pos

    @pos.setter
    def pos(self, pos):
        """Sets the pos of this CustomFieldDisplayOptions.


        :param pos: The pos of this CustomFieldDisplayOptions.  # noqa: E501
        :type: float
        """

        self._pos = pos

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomFieldDisplayOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomFieldDisplayOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
