# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomFieldsIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'pos': 'PosStringOrNumber',
        'displaycard_front': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'pos': 'pos',
        'displaycard_front': 'display/cardFront'
    }

    def __init__(self, name=None, pos=None, displaycard_front=None):  # noqa: E501
        """CustomFieldsIdBody - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._pos = None
        self._displaycard_front = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if pos is not None:
            self.pos = pos
        if displaycard_front is not None:
            self.displaycard_front = displaycard_front

    @property
    def name(self):
        """Gets the name of this CustomFieldsIdBody.  # noqa: E501

        The name of the Custom Field  # noqa: E501

        :return: The name of this CustomFieldsIdBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomFieldsIdBody.

        The name of the Custom Field  # noqa: E501

        :param name: The name of this CustomFieldsIdBody.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def pos(self):
        """Gets the pos of this CustomFieldsIdBody.  # noqa: E501


        :return: The pos of this CustomFieldsIdBody.  # noqa: E501
        :rtype: PosStringOrNumber
        """
        return self._pos

    @pos.setter
    def pos(self, pos):
        """Sets the pos of this CustomFieldsIdBody.


        :param pos: The pos of this CustomFieldsIdBody.  # noqa: E501
        :type: PosStringOrNumber
        """

        self._pos = pos

    @property
    def displaycard_front(self):
        """Gets the displaycard_front of this CustomFieldsIdBody.  # noqa: E501

        Whether to display this custom field on the front of cards  # noqa: E501

        :return: The displaycard_front of this CustomFieldsIdBody.  # noqa: E501
        :rtype: bool
        """
        return self._displaycard_front

    @displaycard_front.setter
    def displaycard_front(self, displaycard_front):
        """Sets the displaycard_front of this CustomFieldsIdBody.

        Whether to display this custom field on the front of cards  # noqa: E501

        :param displaycard_front: The displaycard_front of this CustomFieldsIdBody.  # noqa: E501
        :type: bool
        """

        self._displaycard_front = displaycard_front

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomFieldsIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomFieldsIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
