# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomFieldDisplay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'card_front': 'bool',
        'name': 'str',
        'pos': 'str',
        'options': 'list[CustomFieldDisplayOptions]'
    }

    attribute_map = {
        'card_front': 'cardFront',
        'name': 'name',
        'pos': 'pos',
        'options': 'options'
    }

    def __init__(self, card_front=None, name=None, pos=None, options=None):  # noqa: E501
        """CustomFieldDisplay - a model defined in Swagger"""  # noqa: E501
        self._card_front = None
        self._name = None
        self._pos = None
        self._options = None
        self.discriminator = None
        if card_front is not None:
            self.card_front = card_front
        if name is not None:
            self.name = name
        if pos is not None:
            self.pos = pos
        if options is not None:
            self.options = options

    @property
    def card_front(self):
        """Gets the card_front of this CustomFieldDisplay.  # noqa: E501


        :return: The card_front of this CustomFieldDisplay.  # noqa: E501
        :rtype: bool
        """
        return self._card_front

    @card_front.setter
    def card_front(self, card_front):
        """Sets the card_front of this CustomFieldDisplay.


        :param card_front: The card_front of this CustomFieldDisplay.  # noqa: E501
        :type: bool
        """

        self._card_front = card_front

    @property
    def name(self):
        """Gets the name of this CustomFieldDisplay.  # noqa: E501


        :return: The name of this CustomFieldDisplay.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomFieldDisplay.


        :param name: The name of this CustomFieldDisplay.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def pos(self):
        """Gets the pos of this CustomFieldDisplay.  # noqa: E501


        :return: The pos of this CustomFieldDisplay.  # noqa: E501
        :rtype: str
        """
        return self._pos

    @pos.setter
    def pos(self, pos):
        """Sets the pos of this CustomFieldDisplay.


        :param pos: The pos of this CustomFieldDisplay.  # noqa: E501
        :type: str
        """

        self._pos = pos

    @property
    def options(self):
        """Gets the options of this CustomFieldDisplay.  # noqa: E501


        :return: The options of this CustomFieldDisplay.  # noqa: E501
        :rtype: list[CustomFieldDisplayOptions]
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this CustomFieldDisplay.


        :param options: The options of this CustomFieldDisplay.  # noqa: E501
        :type: list[CustomFieldDisplayOptions]
        """

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomFieldDisplay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomFieldDisplay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
