# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EnterpriseIdp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request_signed': 'bool',
        'certificate': 'str',
        'login_url': 'str'
    }

    attribute_map = {
        'request_signed': 'requestSigned',
        'certificate': 'certificate',
        'login_url': 'loginUrl'
    }

    def __init__(self, request_signed=None, certificate=None, login_url=None):  # noqa: E501
        """EnterpriseIdp - a model defined in Swagger"""  # noqa: E501
        self._request_signed = None
        self._certificate = None
        self._login_url = None
        self.discriminator = None
        if request_signed is not None:
            self.request_signed = request_signed
        if certificate is not None:
            self.certificate = certificate
        if login_url is not None:
            self.login_url = login_url

    @property
    def request_signed(self):
        """Gets the request_signed of this EnterpriseIdp.  # noqa: E501


        :return: The request_signed of this EnterpriseIdp.  # noqa: E501
        :rtype: bool
        """
        return self._request_signed

    @request_signed.setter
    def request_signed(self, request_signed):
        """Sets the request_signed of this EnterpriseIdp.


        :param request_signed: The request_signed of this EnterpriseIdp.  # noqa: E501
        :type: bool
        """

        self._request_signed = request_signed

    @property
    def certificate(self):
        """Gets the certificate of this EnterpriseIdp.  # noqa: E501


        :return: The certificate of this EnterpriseIdp.  # noqa: E501
        :rtype: str
        """
        return self._certificate

    @certificate.setter
    def certificate(self, certificate):
        """Sets the certificate of this EnterpriseIdp.


        :param certificate: The certificate of this EnterpriseIdp.  # noqa: E501
        :type: str
        """

        self._certificate = certificate

    @property
    def login_url(self):
        """Gets the login_url of this EnterpriseIdp.  # noqa: E501


        :return: The login_url of this EnterpriseIdp.  # noqa: E501
        :rtype: str
        """
        return self._login_url

    @login_url.setter
    def login_url(self, login_url):
        """Sets the login_url of this EnterpriseIdp.


        :param login_url: The login_url of this EnterpriseIdp.  # noqa: E501
        :type: str
        """

        self._login_url = login_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnterpriseIdp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnterpriseIdp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
