# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IdNotificationsChannelSettingsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel': 'Channel',
        'blocked_keys': 'OneOfidNotificationsChannelSettingsBodyBlockedKeys'
    }

    attribute_map = {
        'channel': 'channel',
        'blocked_keys': 'blockedKeys'
    }

    def __init__(self, channel=None, blocked_keys=None):  # noqa: E501
        """IdNotificationsChannelSettingsBody - a model defined in Swagger"""  # noqa: E501
        self._channel = None
        self._blocked_keys = None
        self.discriminator = None
        self.channel = channel
        self.blocked_keys = blocked_keys

    @property
    def channel(self):
        """Gets the channel of this IdNotificationsChannelSettingsBody.  # noqa: E501


        :return: The channel of this IdNotificationsChannelSettingsBody.  # noqa: E501
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this IdNotificationsChannelSettingsBody.


        :param channel: The channel of this IdNotificationsChannelSettingsBody.  # noqa: E501
        :type: Channel
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def blocked_keys(self):
        """Gets the blocked_keys of this IdNotificationsChannelSettingsBody.  # noqa: E501

        Blocked key or array of blocked keys.  # noqa: E501

        :return: The blocked_keys of this IdNotificationsChannelSettingsBody.  # noqa: E501
        :rtype: OneOfidNotificationsChannelSettingsBodyBlockedKeys
        """
        return self._blocked_keys

    @blocked_keys.setter
    def blocked_keys(self, blocked_keys):
        """Sets the blocked_keys of this IdNotificationsChannelSettingsBody.

        Blocked key or array of blocked keys.  # noqa: E501

        :param blocked_keys: The blocked_keys of this IdNotificationsChannelSettingsBody.  # noqa: E501
        :type: OneOfidNotificationsChannelSettingsBodyBlockedKeys
        """
        if blocked_keys is None:
            raise ValueError("Invalid value for `blocked_keys`, must not be `None`")  # noqa: E501

        self._blocked_keys = blocked_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdNotificationsChannelSettingsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdNotificationsChannelSettingsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
