# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ImageDescriptor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'width': 'int',
        'height': 'int',
        'url': 'str'
    }

    attribute_map = {
        'width': 'width',
        'height': 'height',
        'url': 'url'
    }

    def __init__(self, width=None, height=None, url=None):  # noqa: E501
        """ImageDescriptor - a model defined in Swagger"""  # noqa: E501
        self._width = None
        self._height = None
        self._url = None
        self.discriminator = None
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if url is not None:
            self.url = url

    @property
    def width(self):
        """Gets the width of this ImageDescriptor.  # noqa: E501

        The width of the image.  # noqa: E501

        :return: The width of this ImageDescriptor.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this ImageDescriptor.

        The width of the image.  # noqa: E501

        :param width: The width of this ImageDescriptor.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this ImageDescriptor.  # noqa: E501

        The height of the image.  # noqa: E501

        :return: The height of this ImageDescriptor.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ImageDescriptor.

        The height of the image.  # noqa: E501

        :param height: The height of this ImageDescriptor.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def url(self):
        """Gets the url of this ImageDescriptor.  # noqa: E501

        The URL of the image.  # noqa: E501

        :return: The url of this ImageDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ImageDescriptor.

        The URL of the image.  # noqa: E501

        :param url: The url of this ImageDescriptor.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImageDescriptor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageDescriptor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
