# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MemberPrefsTwoFactor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'needs_new_backups': 'bool'
    }

    attribute_map = {
        'enabled': 'enabled',
        'needs_new_backups': 'needsNewBackups'
    }

    def __init__(self, enabled=None, needs_new_backups=None):  # noqa: E501
        """MemberPrefsTwoFactor - a model defined in Swagger"""  # noqa: E501
        self._enabled = None
        self._needs_new_backups = None
        self.discriminator = None
        if enabled is not None:
            self.enabled = enabled
        if needs_new_backups is not None:
            self.needs_new_backups = needs_new_backups

    @property
    def enabled(self):
        """Gets the enabled of this MemberPrefsTwoFactor.  # noqa: E501


        :return: The enabled of this MemberPrefsTwoFactor.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this MemberPrefsTwoFactor.


        :param enabled: The enabled of this MemberPrefsTwoFactor.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def needs_new_backups(self):
        """Gets the needs_new_backups of this MemberPrefsTwoFactor.  # noqa: E501


        :return: The needs_new_backups of this MemberPrefsTwoFactor.  # noqa: E501
        :rtype: bool
        """
        return self._needs_new_backups

    @needs_new_backups.setter
    def needs_new_backups(self, needs_new_backups):
        """Sets the needs_new_backups of this MemberPrefsTwoFactor.


        :param needs_new_backups: The needs_new_backups of this MemberPrefsTwoFactor.  # noqa: E501
        :type: bool
        """

        self._needs_new_backups = needs_new_backups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MemberPrefsTwoFactor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MemberPrefsTwoFactor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
