# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NotificationChannelSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'id_member': 'TrelloID',
        'blocked_keys': 'list[BlockedKey]',
        'channel': 'Channel'
    }

    attribute_map = {
        'id': 'id',
        'id_member': 'idMember',
        'blocked_keys': 'blockedKeys',
        'channel': 'channel'
    }

    def __init__(self, id=None, id_member=None, blocked_keys=None, channel=None):  # noqa: E501
        """NotificationChannelSettings - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._id_member = None
        self._blocked_keys = None
        self._channel = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if id_member is not None:
            self.id_member = id_member
        if blocked_keys is not None:
            self.blocked_keys = blocked_keys
        if channel is not None:
            self.channel = channel

    @property
    def id(self):
        """Gets the id of this NotificationChannelSettings.  # noqa: E501


        :return: The id of this NotificationChannelSettings.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NotificationChannelSettings.


        :param id: The id of this NotificationChannelSettings.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def id_member(self):
        """Gets the id_member of this NotificationChannelSettings.  # noqa: E501


        :return: The id_member of this NotificationChannelSettings.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id_member

    @id_member.setter
    def id_member(self, id_member):
        """Sets the id_member of this NotificationChannelSettings.


        :param id_member: The id_member of this NotificationChannelSettings.  # noqa: E501
        :type: TrelloID
        """

        self._id_member = id_member

    @property
    def blocked_keys(self):
        """Gets the blocked_keys of this NotificationChannelSettings.  # noqa: E501


        :return: The blocked_keys of this NotificationChannelSettings.  # noqa: E501
        :rtype: list[BlockedKey]
        """
        return self._blocked_keys

    @blocked_keys.setter
    def blocked_keys(self, blocked_keys):
        """Sets the blocked_keys of this NotificationChannelSettings.


        :param blocked_keys: The blocked_keys of this NotificationChannelSettings.  # noqa: E501
        :type: list[BlockedKey]
        """

        self._blocked_keys = blocked_keys

    @property
    def channel(self):
        """Gets the channel of this NotificationChannelSettings.  # noqa: E501


        :return: The channel of this NotificationChannelSettings.  # noqa: E501
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this NotificationChannelSettings.


        :param channel: The channel of this NotificationChannelSettings.  # noqa: E501
        :type: Channel
        """

        self._channel = channel

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NotificationChannelSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationChannelSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
