# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PendingOrganizationsTransferabilityNewBillableMembers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'TrelloID',
        'full_name': 'str',
        'username': 'str',
        'initials': 'str',
        'avatar_hash': 'str'
    }

    attribute_map = {
        'id': 'id',
        'full_name': 'fullName',
        'username': 'username',
        'initials': 'initials',
        'avatar_hash': 'avatarHash'
    }

    def __init__(self, id=None, full_name=None, username=None, initials=None, avatar_hash=None):  # noqa: E501
        """PendingOrganizationsTransferabilityNewBillableMembers - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._full_name = None
        self._username = None
        self._initials = None
        self._avatar_hash = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if full_name is not None:
            self.full_name = full_name
        if username is not None:
            self.username = username
        if initials is not None:
            self.initials = initials
        if avatar_hash is not None:
            self.avatar_hash = avatar_hash

    @property
    def id(self):
        """Gets the id of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501


        :return: The id of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PendingOrganizationsTransferabilityNewBillableMembers.


        :param id: The id of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :type: TrelloID
        """

        self._id = id

    @property
    def full_name(self):
        """Gets the full_name of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501


        :return: The full_name of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this PendingOrganizationsTransferabilityNewBillableMembers.


        :param full_name: The full_name of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def username(self):
        """Gets the username of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501


        :return: The username of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this PendingOrganizationsTransferabilityNewBillableMembers.


        :param username: The username of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def initials(self):
        """Gets the initials of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501


        :return: The initials of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :rtype: str
        """
        return self._initials

    @initials.setter
    def initials(self, initials):
        """Sets the initials of this PendingOrganizationsTransferabilityNewBillableMembers.


        :param initials: The initials of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :type: str
        """

        self._initials = initials

    @property
    def avatar_hash(self):
        """Gets the avatar_hash of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501


        :return: The avatar_hash of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :rtype: str
        """
        return self._avatar_hash

    @avatar_hash.setter
    def avatar_hash(self, avatar_hash):
        """Sets the avatar_hash of this PendingOrganizationsTransferabilityNewBillableMembers.


        :param avatar_hash: The avatar_hash of this PendingOrganizationsTransferabilityNewBillableMembers.  # noqa: E501
        :type: str
        """

        self._avatar_hash = avatar_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PendingOrganizationsTransferabilityNewBillableMembers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PendingOrganizationsTransferabilityNewBillableMembers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
