# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PluginData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'TrelloID',
        'id_plugin': 'TrelloID',
        'scope': 'str',
        'id_model': 'TrelloID',
        'value': 'str',
        'access': 'str'
    }

    attribute_map = {
        'id': 'id',
        'id_plugin': 'idPlugin',
        'scope': 'scope',
        'id_model': 'idModel',
        'value': 'value',
        'access': 'access'
    }

    def __init__(self, id=None, id_plugin=None, scope=None, id_model=None, value=None, access=None):  # noqa: E501
        """PluginData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._id_plugin = None
        self._scope = None
        self._id_model = None
        self._value = None
        self._access = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if id_plugin is not None:
            self.id_plugin = id_plugin
        if scope is not None:
            self.scope = scope
        if id_model is not None:
            self.id_model = id_model
        if value is not None:
            self.value = value
        if access is not None:
            self.access = access

    @property
    def id(self):
        """Gets the id of this PluginData.  # noqa: E501


        :return: The id of this PluginData.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PluginData.


        :param id: The id of this PluginData.  # noqa: E501
        :type: TrelloID
        """

        self._id = id

    @property
    def id_plugin(self):
        """Gets the id_plugin of this PluginData.  # noqa: E501


        :return: The id_plugin of this PluginData.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id_plugin

    @id_plugin.setter
    def id_plugin(self, id_plugin):
        """Sets the id_plugin of this PluginData.


        :param id_plugin: The id_plugin of this PluginData.  # noqa: E501
        :type: TrelloID
        """

        self._id_plugin = id_plugin

    @property
    def scope(self):
        """Gets the scope of this PluginData.  # noqa: E501


        :return: The scope of this PluginData.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this PluginData.


        :param scope: The scope of this PluginData.  # noqa: E501
        :type: str
        """
        allowed_values = ["member", "board", "organization", "card"]  # noqa: E501
        if scope not in allowed_values:
            raise ValueError(
                "Invalid value for `scope` ({0}), must be one of {1}"  # noqa: E501
                .format(scope, allowed_values)
            )

        self._scope = scope

    @property
    def id_model(self):
        """Gets the id_model of this PluginData.  # noqa: E501


        :return: The id_model of this PluginData.  # noqa: E501
        :rtype: TrelloID
        """
        return self._id_model

    @id_model.setter
    def id_model(self, id_model):
        """Sets the id_model of this PluginData.


        :param id_model: The id_model of this PluginData.  # noqa: E501
        :type: TrelloID
        """

        self._id_model = id_model

    @property
    def value(self):
        """Gets the value of this PluginData.  # noqa: E501


        :return: The value of this PluginData.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this PluginData.


        :param value: The value of this PluginData.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def access(self):
        """Gets the access of this PluginData.  # noqa: E501


        :return: The access of this PluginData.  # noqa: E501
        :rtype: str
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this PluginData.


        :param access: The access of this PluginData.  # noqa: E501
        :type: str
        """
        allowed_values = ["private", "shared"]  # noqa: E501
        if access not in allowed_values:
            raise ValueError(
                "Invalid value for `access` ({0}), must be one of {1}"  # noqa: E501
                .format(access, allowed_values)
            )

        self._access = access

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PluginData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PluginData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
