# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import trello_api_client
from trello_api_client.models.value1 import Value1  # noqa: E501
from trello_api_client.rest import ApiException


class TestValue1(unittest.TestCase):
    """Value1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValue1(self):
        """Test Value1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = trello_api_client.models.value1.Value1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
