# coding: utf-8

"""
    Trello REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import trello_api_client
from trello_api_client.models.action_data_list import ActionDataList  # noqa: E501
from trello_api_client.rest import ApiException


class TestActionDataList(unittest.TestCase):
    """ActionDataList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionDataList(self):
        """Test ActionDataList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = trello_api_client.models.action_data_list.ActionDataList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
